mac: 
	g++ -framework Foundation -framework GLUT -framework OpenGL -lOpenImageIO -lm main.cpp -std=c++17

linux: 
	g++ -L /usr/lib64/ -lglut -lGL -lGLU -lOpenImageIO -lm main.cpp -std=c++17

clean:
	rm a.out