default: 
	javac cpsc2150/ExtendedTicTacToe/IGameBoard.java cpsc2150/ExtendedTicTacToe/GameBoard.java cpsc2150/ExtendedTicTacToe/GameBoardMem.java cpsc2150/ExtendedTicTacToe/AbsGameBoard.java cpsc2150/ExtendedTicTacToe/BoardPosition.java cpsc2150/ExtendedTicTacToe/GameScreen.java
	
run:
	java cpsc2150.ExtendedTicTacToe.GameScreen

test:
	javac cpsc2150/ExtendedTicTacToe/IGameBoard.java cpsc2150/ExtendedTicTacToe/GameBoard.java cpsc2150/ExtendedTicTacToe/GameBoardMem.java cpsc2150/ExtendedTicTacToe/AbsGameBoard.java cpsc2150/ExtendedTicTacToe/BoardPosition.java cpsc2150/ExtendedTicTacToe/GameScreen.java cpsc2150/ExtendedTicTacToe/TestGameBoard.java cpsc2150/ExtendedTicTacToe/TestMemBoard.java
	

java  -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore cpsc2150.MyQueue.TestGameBoard
java  -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore cpsc2150.MyQueue.TestMemBoard

testGB:
	javac cpsc2150/ExtendedTicTacToe/IGameBoard.java cpsc2150/ExtendedTicTacToe/GameBoard.java cpsc2150/ExtendedTicTacToe/GameBoardMem.java cpsc2150/ExtendedTicTacToe/AbsGameBoard.java cpsc2150/ExtendedTicTacToe/BoardPosition.java cpsc2150/ExtendedTicTacToe/GameScreen.java cpsc2150/ExtendedTicTacToe/TestGameBoard.java cpsc2150/ExtendedTicTacToe/TestMemBoard.java
java  -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore cpsc2150.MyQueue.TestGameBoard

testGBMem:
	javac cpsc2150/ExtendedTicTacToe/IGameBoard.java cpsc2150/ExtendedTicTacToe/GameBoard.java cpsc2150/ExtendedTicTacToe/GameBoardMem.java cpsc2150/ExtendedTicTacToe/AbsGameBoard.java cpsc2150/ExtendedTicTacToe/BoardPosition.java cpsc2150/ExtendedTicTacToe/GameScreen.java cpsc2150/ExtendedTicTacToe/TestGameBoard.java cpsc2150/ExtendedTicTacToe/TestMemBoard.java
java  -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore cpsc2150.MyQueue.TestMemBoard

clean:
	$(RM) cpsc2150/ExtendedTicTacToe/*.class
