default: 
	javac cpsc2150/MyQueue/IQueue.java cpsc2150/MyQueue/ListQueue.java cpsc2150/MyQueue/ArrayQueue.java cpsc2150/MyQueue/AbsQueue.java cpsc2150/MyQueue/QueueApp.java cpsc2150/MyQueue/DoubleQueueApp.java
	
runInt:
	java cpsc2150.MyQueue.QueueApp 
runDouble:
	java cpsc2150.MyQueue.DoubleQueueApp

clean:
	$(RM) cpsc2150/MyQueue/*.class
