default: 
	javac cpsc2150/MyQueue/IQueue.java cpsc2150/MyQueue/ListQueue.java cpsc2150/MyQueue/ArrayQueue.java cpsc2150/MyQueue/QueueApp.java
	java cpsc2150.MyQueue.QueueApp
clean:
	$(RM) cpsc2150/MyQueue/*.class
